token: ""
path:
- F:\
- G:\
apiKey: a8295ca6-91ad-4524-8db7-4cff86068e51
cachePath: ""
deviceId: ""
extraParams: {}
log:
  lv: info
  path: ./log/
  name: miner.log
url:
  info: ""
  submit: ""
  line: ""
  ws: ""
scanPath: true
scanMinute: 120
debug: ""
language: en
multithreadingLoad: false
